apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: erpnext-prod
  namespace: erpnext
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: ./erpnext
      sourceRef:
        kind: GitRepository
        name: frappe-helm-chart
        namespace: erpnext
      reconcileStrategy: Revision
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: erpnext-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: erpnext-hpa-values
      valuesKey: hpa-values.yaml
