apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: erpnext
resources:
  - source.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: erpnext-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
