image:
  repository: didin8080/frappe-build-test
  tag: "1"
  pullPolicy: IfNotPresent

mariadb:
  enabled: false
mariadb-subchart:
  enabled: false

dbHost: "192.168.0.133"
dbPort: 3306
dbRootUser: "appuser"
dbExistingSecret: "proxysql-root-secret"
dbExistingSecretPasswordKey: "mariadb-root-password"

persistence:
  worker:
    enabled: true
    storageClass: "nfs-client"

jobs:
  configureBench:
    enabled: true
  createSite:
    enabled: false
  createMultipleSites:
    enabled: true
    dbType: "mariadb"
    adminPassword: "Bizaxltest"
    sites:
      - name: "demo.site"
        installApps: ["erpnext","hrms"]
      - name: "sinchana-demo.site"
        installApps: ["erpnext","hrms"]

  migrateMultipleSites:
    enabled: true
    skipFailing: false
    sites:
      - name: "demo.site"
      - name: "sinchana-demo.site"
    backoffLimit: 0
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "$host"
  hosts:
    - host: demo.site
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: sinchana-demo.site
      paths:
        - path: /
          pathType: ImplementationSpecific


nginx:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-nginx
          app.kubernetes.io/instance: erpnext-prod-nginx

worker:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-gunicorn
          app.kubernetes.io/instance: erpnext-prod-gunicorn

valkey-cache:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
valkey-queue:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
