image:
  repository: benedictdockeracc/custom
  tag: "16.2.0"
  pullPolicy: IfNotPresent

mariadb:
  enabled: false
mariadb-subchart:
  enabled: false

dbHost: "192.168.0.133"
dbPort: 3306
dbRootUser: "appuser"
dbExistingSecret: "proxysql-root-secret"
dbExistingSecretPasswordKey: "mariadb-root-password"

persistence:
  worker:
    enabled: true
    storageClass: "nfs-client"

jobs:
  configureBench:
    enabled: true
  createSite:
    enabled: false
  createMultipleSites:
    enabled: true
    dbType: "mariadb"
    adminPassword: "Bizaxltest"
    sites:
      - name: "site1.company.local"
        installApps: ["erpnext", "payments"]
      - name: "site2.company.local"
        installApps: ["erpnext", "hrms"]

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "$host"
  hosts:
    - host: site1.company.local
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: site2.company.local
      paths:
        - path: /
          pathType: ImplementationSpecific

nginx:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-nginx
          app.kubernetes.io/instance: erpnext-prod-nginx

worker:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-gunicorn
          app.kubernetes.io/instance: erpnext-prod-gunicorn
