image:
  repository: didin8080/frappe-build-test
  tag: "1"
  pullPolicy: IfNotPresent

mariadb:
  enabled: false
mariadb-subchart:
  enabled: false
mariadb-sts:
  enabled: false
postgresql:
  enabled: false
postgresql-subchart:
  enabled: false
postgresql-sts:
  enabled: false

dbHost: "192.168.0.136"
dbPort: 6033
dbRootUser: "appuser"
dbExistingSecret: "proxysql-root-secret"
dbExistingSecretPasswordKey: "mariadb-root-password"

persistence:
  worker:
    enabled: true
    storageClass: "nfs-client"

jobs:
  configure:
    enabled: true
  createSite:
    enabled: false
  createMultipleSites:
    enabled: true
    dbType: "mariadb"
    adminPassword: "Bizaxltest"
    backoffLimit: 3
    sites:
#      - name: "site.testsite"
#        installApps: []
#      - name: "proxy.site"
#        installApps: []
#      - name: "proxy5.site"
#        installApps: []
  migrateMultipleSites:
    enabled: false
    skipFailing: false
    sites:
#      - name: "proxy4.site"
#    backoffLimit: 0
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "$host"
  hosts:
    - host: site.testsite
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: blacky.testsite
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: proxy.site
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: proxy5.site
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: proxy4.site
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: proxy.site4.test
      paths:
        - path: /
          pathType: ImplementationSpecific
nginx:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-nginx
          app.kubernetes.io/instance: erpnext-prod-nginx

worker:
  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: erpnext-gunicorn
          app.kubernetes.io/instance: erpnext-prod-gunicorn

valkey-cache:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
valkey-queue:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
